# Generated by Django 5.1.1 on 2024-09-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_servis', models.DateField()),
                ('jenis_servis', models.CharField(choices=[('Umum', 'Servis Umum'), ('Rutin', 'Servis Berkala'), ('Darurat', 'Servis Darurat'), ('Perbaikan', 'Perbaikan Spesifik')], max_length=50)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autowin.pelanggan')),
            ],
        ),
    ]
