# Generated by Django 5.1.1 on 2024-09-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='servis',
            name='pelanggan',
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='autowin.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Pelanggan',
        ),
        migrations.DeleteModel(
            name='Servis',
        ),
    ]
