# Generated by Django 5.1.1 on 2024-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowin', '0002_service_remove_servis_pelanggan_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='service',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='pesan',
            new_name='komentar',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='nama_pelanggan',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='pekerjaan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
