# Generated by Django 5.1.1 on 2024-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowin', '0005_alter_pelanggan_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='no_hp',
            field=models.CharField(max_length=30),
        ),
    ]
