# Generated by Django 5.1.1 on 2024-10-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowin', '0006_alter_pelanggan_no_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('keterangan', models.TextField()),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autowin.servis')),
            ],
        ),
    ]
